version: '3.8'

services:
  # BFF Service
  bff-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bff-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth-service:8080}
      - DATA_RETRIEVAL_SERVICE_URL=${DATA_RETRIEVAL_SERVICE_URL:-http://data-retrieval-api:8000}
      - AUTH_TOKEN=${AUTH_TOKEN:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkJGRiBTZXJ2aWNlIiwiaWF0IjoxNjE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - data_retrieval_network

networks:
  data_retrieval_network:
    external: true