### Variables
@host = https://bff-retrieval-app-1017406670325.us-central1.run.app
#@host = http://localhost:8004
@authHost = https://auth-app-1017406670325.us-central1.run.app
@dataRetrievalHost = https://data-retrieval-app-1017406670325.us-central1.run.app

@taskId = 33b3e660-c4a2-4a11-8864-63b253f50894

### Verificación de salud del BFF
GET {{host}}/health

### ---------------------------------------------------
### ENDPOINTS DEL BFF
### ---------------------------------------------------

### Crear Tarea de Recuperación
# @name createTask
POST {{host}}/api/bff/v1/data-retrieval/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkRhdGFQYXJ0bmVyIn0.BnLA0KJC3-fQBzpK0KfSO0p4s-KUEHNlpdvUx0Qkzsk
Content-Type: application/json

{
  "source_type": "HOSPITAL",
  "source_name": "Hospital San Juan de Dios",
  "source_id": "HSJ-001",
  "location": "Bogotá",
  "retrieval_method": "DIRECT_UPLOAD",
  "batch_id": "BATCH-2025-010",
  "priority": 2,
  "metadata": {
    "department": "Radiología",
    "project": "Estudio COVID-2025"
  }
}
### Obtener un batch específico
# @name GetBatch
GET {{host}}/api/bff/v1/data-retrieval/tasks?batch_id={{createTask.request.body.batch_id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkRhdGFQYXJ0bmVyIn0.BnLA0KJC3-fQBzpK0KfSO0p4s-KUEHNlpdvUx0Qkzsk
Content-Type: application/json

### Iniciar Tarea
POST {{host}}/api/bff/v1/data-retrieval/tasks/{{taskId}}/start
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkRhdGFQYXJ0bmVyIn0.BnLA0KJC3-fQBzpK0KfSO0p4s-KUEHNlpdvUx0Qkzsk
Content-Type: application/json

{}

### Subir Imagen a Tarea
POST {{host}}/api/bff/v1/data-retrieval/tasks/{{taskId}}/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkRhdGFQYXJ0bmVyIn0.BnLA0KJC3-fQBzpK0KfSO0p4s-KUEHNlpdvUx0Qkzsk
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="format"

DICOM
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="modality"

MRI
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="region"

CHEST
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dimensions"

1024x768
------WebKitFormBoundary7MA4YWxkTrZu0gW--
